plugins {
    id 'com.android.application'
}

android {
    namespace 'com.cometinhastudios.wudroid'
    compileSdk 35

    defaultConfig {
        applicationId 'com.cometinhastudios.wudroid'
        minSdk 24
        targetSdk 35
        versionCode 4
        versionName '0.0.4'
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
